version: '3.4'

services:
  pcf.receivingfrompartner.webhost:
    image: ${DOCKER_REGISTRY-}pcfreceivingfrompartnerwebhost
    build:
      context: .
      dockerfile: Pcf.ReceivingFromPartner.WebHost\Dockerfile
